"""WRITE_DOWN_EXPLANATIONS

Revision ID: 227ca71fa95c
Revises: 6a33f5a1e51e
Create Date: 2022-08-15 09:57:05.871837

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '227ca71fa95c'
down_revision = '6a33f5a1e51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cognito_user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True))
    op.create_unique_constraint(None, 'users', ['cognito_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cognito_user_id')
    # ### end Alembic commands ###
