"""WRITE_DOWN_EXPLANATIONS

Revision ID: 6a33f5a1e51e
Revises: a3898b22b080
Create Date: 2022-08-10 21:02:57.061732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a33f5a1e51e'
down_revision = 'a3898b22b080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
