"""WRITE_DOWN_EXPLANATIONS

Revision ID: a3898b22b080
Revises: ad72e8d14d46
Create Date: 2022-08-10 21:01:19.740712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3898b22b080'
down_revision = 'ad72e8d14d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
