"""WRITE_DOWN_EXPLANATIONS

Revision ID: ad72e8d14d46
Revises: 686ab60a1679
Create Date: 2022-08-10 20:56:51.479177

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = 'ad72e8d14d46'
down_revision = '686ab60a1679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_curriculums', sa.Column('week_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False))
    op.create_foreign_key(None, 'input_curriculums', 'weeks', ['week_id'], ['uuid'])
    op.add_column('output_curriculums', sa.Column('week_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False))
    op.create_foreign_key(None, 'output_curriculums', 'weeks', ['week_id'], ['uuid'])
    op.create_unique_constraint(None, 'weeks', ['week'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weeks', type_='unique')
    op.drop_constraint(None, 'output_curriculums', type_='foreignkey')
    op.drop_column('output_curriculums', 'week_id')
    op.drop_constraint(None, 'input_curriculums', type_='foreignkey')
    op.drop_column('input_curriculums', 'week_id')
    # ### end Alembic commands ###
