"""WRITE_DOWN_EXPLANATIONS

Revision ID: dabd94526db8
Revises: 160be9072d47
Create Date: 2022-08-15 15:45:35.242661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabd94526db8'
down_revision = '160be9072d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posse_years', ['year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posse_years', type_='unique')
    # ### end Alembic commands ###
